// Question Link : https://codeforces.com/problemset/problem/1430/C

// Explanation
// By observation, we can conclude that the minimum possible number left on the whiteboard is always 2.
// The slightly tricky part is printing the pairs of numbers that should be chosen for each operation.
// In each operation, we choose two numbers a and b and replace them with (a + b) / 2, rounded down if the result is not an integer.
// For the first two operations, the first number is always n, while the second number is n - j, where 1 <= j <= 2.
// After the first two operations, the first number becomes n - j + 2, while the second number remains n - j.
// Therefore, the operations generated by the code follow this pattern.
// For example, when n = 4, the operations are:
// a = 4, b = 3
// a = 4, b = 2
// a = 3, b = 1
// The solution is mainly based on observation, and the code prints the required n - 1 operations directly.
import java.util.*;
public class NumbersOnWhiteboard {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int t = sc.nextInt();
        for(int i = 1; i <= t; i++) {
            int n = sc.nextInt();
            System.out.println(2);
            for(int j = 1; j <= n - 1; j++) {
                if(j <= 2) {
                    System.out.println(n + " " + (n - j));
                }
                else {
                    System.out.println((n - j + 2) + " " + (n - j));
                }
            }
        }
        sc.close();
    }   
}